apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: tomcat-app
        image: vizzbob/my-tomcat-app
        ports:
        - containerPort: 8080
